export const types = Object.freeze({
    // Sync
    PLANETS_START_FETCHING: 'PLANETS_START_FETCHING',
    PLANETS_STOP_FETCHING: 'PLANETS_STOP_FETCHING',
    PLANETS_FILL: 'PLANETS_FILL',
    PLANETS_SET_FETCHING_ERROR: 'PLANETS_SET_FETCHING_ERROR',
    // Async
    PLANETS_FETCH_ASYNC: 'PLANETS_FETCH_ASYNC'
});